eureka:
  client:
    service-url: #像eureka 服务端注册服务
       defaultZone: http://localhost:8761/eureka/,http://localhost:8764/eureka/
server:
  port: 8888 #应用服务端口
spring:
  application: #应用名称
    name: config-server
  zipkin:
    base-url: http://localhost:9441
  sleuth:
    sampler:
      probability: 1.0
  boot:
    admin:
    #服务端地址
      client:
        url:
        - http://127.0.0.1:8843
  cloud: #config服务端，从git拉取数据
    config:
      server:
        git: #配置远程git仓库  公开库不需要配置账号密码  私有库需要配置   公开库配置可提升访问速度
          uri: https://github.com/mrqiang1/my-Hello-Word #配置git仓库地址
          search-paths:
          - spring-cloud/helloworldConfig #git仓库的搜索目录
          default-label: master #默认分支
          username: 18894312938@163.com #账号
          password: wenqiang123 #密码
  rabbitmq: #配置mq，需要启动mq服务
    host: localhost #rabbitmq主机地址
    port: 5762 #服务端口
    username: wangwq20 #账号
    password: wangwq20 #密码
    virtual-host: / #虚拟主机
    addresses: 127.0.0.1
management:
  cloudfoundry: #是否开启基本的鉴权，默认为true
    enabled: true
  endpoints: #SpringCloud 2.0.0版本以后暴露接口方式
    web:
      exposure:
        include:
        #- refresh,bus-refresh
        - "*" #暴露所有接口 不安全  生产环境根据需要暴露
    