
spring:
  application:
    name: micoserice-zipkin-server
  sleuth:
    sampler:
      probability: 1.0
  boot:
    admin:
    #服务端地址
      client:
        url:
        - http://127.0.0.1:8843

server:
  port: 9441
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8764/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false